package com.square.repos.ui.theme

import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFF006A6A)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFF6FF7F6)
val onPrimaryContainerLight = Color(0xFF002020)

val secondaryLight = Color(0xFF4A6363)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFCCE8E7)
val onSecondaryContainerLight = Color(0xFF051F1F)

val tertiaryLight = Color(0xFF4A607C)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFD2E4FF)
val onTertiaryContainerLight = Color(0xFF031D35)

val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF410002)

val backgroundLight = Color(0xFFFAFDFB)
val onBackgroundLight = Color(0xFF191C1C)
val surfaceLight = Color(0xFFFAFDFB)
val onSurfaceLight = Color(0xFF191C1C)
val surfaceVariantLight = Color(0xFFDAE5E4)
val onSurfaceVariantLight = Color(0xFF3F4948)
val outlineLight = Color(0xFF6F7979)
val outlineVariantLight = Color(0xFFBEC9C8)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF2E3131)
val inverseOnSurfaceLight = Color(0xFFEFF1F0)
val inversePrimaryLight = Color(0xFF4DDAD9)
val surfaceDimLight = Color(0xFFDADDDC)
val surfaceBrightLight = Color(0xFFFAFDFB)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF4F7F6)
val surfaceContainerLight = Color(0xFFEEF1F0)
val surfaceContainerHighLight = Color(0xFFE8ECEB)
val surfaceContainerHighestLight = Color(0xFFE2E6E5)

val primaryDark = Color(0xFF4DDAD9)
val onPrimaryDark = Color(0xFF003737)
val primaryContainerDark = Color(0xFF00504F)
val onPrimaryContainerDark = Color(0xFF6FF7F6)

val secondaryDark = Color(0xFFB0CCCB)
val onSecondaryDark = Color(0xFF1B3534)
val secondaryContainerDark = Color(0xFF324B4A)
val onSecondaryContainerDark = Color(0xFFCCE8E7)

val tertiaryDark = Color(0xFFB2C8E9)
val onTertiaryDark = Color(0xFF1B324B)
val tertiaryContainerDark = Color(0xFF334863)
val onTertiaryContainerDark = Color(0xFFD2E4FF)

val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)

val backgroundDark = Color(0xFF191C1C)
val onBackgroundDark = Color(0xFFE0E3E2)
val surfaceDark = Color(0xFF191C1C)
val onSurfaceDark = Color(0xFFE0E3E2)
val surfaceVariantDark = Color(0xFF3F4948)
val onSurfaceVariantDark = Color(0xFFBEC9C8)
val outlineDark = Color(0xFF899392)
val outlineVariantDark = Color(0xFF3F4948)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFE0E3E2)
val inverseOnSurfaceDark = Color(0xFF191C1C)
val inversePrimaryDark = Color(0xFF006A6A)
val surfaceDimDark = Color(0xFF191C1C)
val surfaceBrightDark = Color(0xFF3F4242)
val surfaceContainerLowestDark = Color(0xFF0F1212)
val surfaceContainerLowDark = Color(0xFF191C1C)
val surfaceContainerDark = Color(0xFF1D2020)
val surfaceContainerHighDark = Color(0xFF272A2A)
val surfaceContainerHighestDark = Color(0xFF323535)
